-- vim.pack.add({
--   {
--     src = "https://github.com/nvim-neorg/neorg",
--     version = vim.version.range("*"),
--   },
--   { src = "https://github.com/nvim-neorg/lua-utils.nvim" },
--   { src = "https://github.com/nvim-neotest/nvim-nio" },
--   { src = "https://github.com/MunifTanjim/nui.nvim" },
--   { src = "https://github.com/nvim-lua/plenary.nvim" },
--   { src = "https://github.com/pysan3/pathlib.nvim" },
--   "nvim-treesitter-legacy-api",
-- }, { confirm = false })
--
-- vim.schedule(function()
--   require("neorg").setup({
--     load = {
--       ["core.defaults"] = {},
--       ["core.dirman"] = {
--         config = {
--           workspaces = {
--             notes = "~/.config/nvim/notes",
--           },
--           default_workspace = "notes",
--           index = "index.norg",
--         },
--       },
--       ["core.concealer"] = {},
--     },
--   })
-- end)
