git:
  paging:
    colorArg: always
    pager: delta --paging=never

customCommands:
  - key: "<c-a>" # ctrl + a
    description: "Generate commit message"
    context: "files"
    loadingText: "Generating commit message..."
    subprocess: true
    prompts:
      - type: "menuFromCommand"
        title: "Copilot AI Commitizen"
        key: "Msg"
        command: copilot-cli --action "lazygit-conventional-commit" --path "."
        filter: '^(?P<number>\d+):\s(?P<type>\w+)(?:\((?P<scope>[^)]+)\))?:\s(?P<message>.+)$'
        valueFormat: "{{ .type }}{{ if .scope }}({{ .scope }}){{ end }}: {{ .message }}"
        labelFormat: "{{ .type | red }}{{ if .scope }}({{ .scope }}){{ end }}: {{ .message | green }}"
      - type: "menu"
        key: "Confirm"
        title: "Confirm/Edit commit message"
        options:
          - name: "Commit"
            value: "commit"
          - name: "Edit"
            value: "edit"
    command: >
      {{- if eq .Form.Confirm "commit" -}}
        git commit -m '{{.Form.Msg}}'
      {{- else if eq .Form.Confirm "edit" -}}
        git commit -e -m '{{.Form.Msg}}'
      {{- else -}}
        echo "Commit cancelled" && exit 0
      {{- end -}}

gui:
  theme:
    activeBorderColor:
      - '#8aadf4'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#8aadf4'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'

