git:
  paging:
    colorArg: always
    pager: delta --paging=never

customCommands:
  - key: "<c-a>" # ctrl + a
    description: "Generate commit message"
    command: "git commit -m '{{.Form.Msg}}'"
    context: "files"
    loadingText: "Generating commit message..."
    subprocess: true
    prompts:
      - type: "menuFromCommand"
        title: "Copilot AI Commitizen"
        key: "Msg"
        command: copilot-chat-cli --action "lazygit-commitizen"
        filter: '^(?P<number>\d+):\s(?P<message>.+)$'
        valueFormat: "{{ .message }}"
        labelFormat: "{{ .number }}: {{ .message | green }}"

gui:
  theme:
    activeBorderColor:
      - '#8aadf4'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#8aadf4'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'

