#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  # Fix escapce sequence issues
  [[blocks.segments]]
  type = "text"
  style = "plain"
  template = "\n"

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'


  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "yellow"
    background = "transparent"
    template = "  {{ .Full }}"

  [[blocks.segments]]
    type = "dotnet"
    style = "plain"
    foreground = "magenta"
    background = "transparent"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "node"
    style = "plain"
    foreground = "green"
    background = "transparent"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'grey'
    background = 'transparent'
  	template = "  {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<pink>*</>{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "


    [blocks.segments.properties]
      commit_icon = '@'
      branch_ahead_icon = "<lightcyan>⇡ </>"
      branch_behind_icon = "<lightcyan>⇣ </>"
      branch_icon = ""
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      github_icon = ""

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = ' 󱦟 {{ .FormattedMs }}'

    [blocks.segments.properties]
      style = "round"
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'command'
    style = 'plain'
    foreground = 'blue'
    background = 'transparent'
    template = '{{ if eq .Output "1" }}  ({{ substr 0 5 .Env.HOSTNAME }}) {{end}}'

    [blocks.segments.properties]
        script = "$HOME/.config/scripts/is_inside_docker.sh"

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "yellow"
    background = "transparent"
    template = "({{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}{{ end }}{{ end }}) "

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

