-- return {
-- 	Text = " ",
-- 	Method = " ",
-- 	Function = "󰊕 ",
-- 	Constructor = " ",
-- 	Field = " ",
-- 	Variable = " ",
-- 	Class = " ",
-- 	Interface = " ",
-- 	Module = "󰏓 ",
-- 	Property = " ",
-- 	Unit = " ",
-- 	Value = "󰎠 ",
-- 	Enum = " ",
-- 	EnumMember = " ",
-- 	Keyword = "󰌋 ",
-- 	Snippet = " ",
-- 	Color = " ",
-- 	File = "󰈙 ",
-- 	Reference = "󰈇 ",
-- 	Folder = " ",
-- 	Constant = "󰏿 ",
-- 	Struct = "󰙅 ",
-- 	Event = " ",
-- 	Operator = " ",
-- 	TypeParameter = "󰘦 ",
-- 	Codeium = " ",
-- 	Version = " ",
-- 	Unknown = "  ",
-- 	Calculator = " ",
-- 	Emoji = "󰞅 ",
-- }

-- Custom
return {
	Text = " ",
	Method = "󰆧 ",
	Function = "󰊕 ",
	Constructor = " ",
	Field = "󰜢 ",
	Variable = "󰀫 ",
	Class = "󰠱 ",
	Interface = " ",
	Module = " ",
	Property = "󰜢 ",
	Unit = "󰑭 ",
	Value = "󰎠 ",
	Enum = " ",
	Keyword = "󰌋 ",
	Snippet = " ",
	Color = "󰏘 ",
	File = "󰈙 ",
	Reference = "󰈇 ",
	Folder = "󰉋 ",
	EnumMember = " ",
	Constant = "󰏿 ",
	Struct = "󰙅 ",
	Event = " ",
	Operator = "󰆕 ",
	TypeParameter = " ",
	Emoji = "󰞅 ",
	Copilot = " ",
}

-- VSCode codicons
-- return {
-- Text = " ",
-- Method = " ",
-- Function = " ",
-- Constructor = " ",
-- Field = " ",
-- Variable = " ",
-- Class = " ",
-- Interface = " ",
-- Module = " ",
-- Property = " ",
-- Unit = " ",
-- Value = " ",
-- Enum = " ",
-- Keyword = " ",
-- Snippet = " ",
-- Color = " ",
-- File = " ",
-- Reference = " ",
-- Folder = " ",
-- EnumMember = " ",
-- Constant = " ",
-- Struct = " ",
-- Event = " ",
-- Operator = " ",
-- TypeParameter = " ",
-- }
