return {
  git = {
    added = " ",
    modified = " ",
    removed = " ",
    renamed = "󰑕 ",
    branch = "",
    ignored = " ",
    unstaged = "󰄱 ",
    staged = " ",
    untracked = "",
  },
  full_diagnostic = {
    ok = "",
    error = "",
    warning = "",
    warn = "",
    info = "",
    hint = "",
  },
  diagnostic = {
    error = "●",
    warning = "●",
    warn = "●",
    info = "●",
    hint = "●",
    ok = "●",
    other = "●",
  },
  others = {
    copilot = " ",
    copilot_disabled = " ",
    terminal = " ",
    folder = "󰉖 ",
    loading = " ",
    checkmark = " ",
    error_x = " ",
  },
}
