local M = {}

M.kind_icons = {
	Text = " ",
	Method = " ",
	Function = "󰊕 ",
	Constructor = " ",
	Field = " ",
	Variable = " ",
	Class = " ",
	Interface = " ",
	Module = "󰏓 ",
	Property = " ",
	Unit = " ",
	Value = "󰎠 ",
	Enum = " ",
	EnumMember = " ",
	Keyword = "󰌋 ",
	Snippet = " ",
	Color = " ",
	File = "󰈙 ",
	Reference = "󰈇 ",
	Folder = " ",
	Constant = "󰏿 ",
	Struct = "󰙅 ",
	Event = " ",
	Operator = " ",
	TypeParameter = "󰘦 ",
	Codeium = " ",
	Version = " ",
	Unknown = "  ",
	Calculator = " ",
	Emoji = "󰞅 ",
}

return M
