local M = {}

function M.get(colors)
  local default_bg = "None"
  local U = require("utils")

  return {
    NormalFloat = { bg = default_bg },
    Pmenu = { bg = default_bg },
    PmenuSbar = { bg = colors.surface },
    PmenuThumb = { bg = colors.subtle },
    FloatBorder = { fg = colors.subtle, bg = default_bg },
    FloatTitle = { bg = default_bg, fg = colors.text, italic = true, bold = true },
    Comment = { fg = colors.muted, italic = true },

    DiffAdd = { bg = U.darken(colors.green, 0.18, colors.base) },
    DiffChange = { bg = U.darken(colors.blue, 0.07, colors.base) },
    DiffDelete = { bg = U.darken(colors.red, 0.18, colors.base) },
    DiffText = { bg = U.darken(colors.blue, 0.30, colors.base) },

    -- Treesitter: Identifiers
    ["@variable"] = { fg = colors.text },
    ["@variable.builtin"] = { fg = colors.red },
    ["@variable.parameter"] = { fg = colors.flamingo },
    ["@variable.member"] = { fg = colors.highlight },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = colors.peach },
    ["@constant.macro"] = { link = "Macro" },
    ["@module"] = { fg = colors.yellow, italic = true },
    ["@namespace"] = { link = "@module" },
    ["@label"] = { link = "Label" },

    -- Treesitter: Literals
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { fg = colors.teal },
    ["@string.regexp"] = { fg = colors.mauve },
    ["@string.escape"] = { fg = colors.mauve },
    ["@string.special"] = { link = "Special" },
    ["@string.special.path"] = { link = "Special" },
    ["@string.special.symbol"] = { fg = colors.flamingo },
    ["@string.special.url"] = { fg = colors.blue, italic = true, underline = true },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },

    -- Treesitter: Types
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = colors.mauve },
    ["@type.definition"] = { link = "Type" },
    ["@attribute"] = { link = "Constant" },
    ["@property"] = { fg = colors.highlight },

    -- Treesitter: Functions
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = colors.peach },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { fg = colors.mauve },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@constructor"] = { fg = colors.yellow },
    ["@operator"] = { link = "Operator" },

    -- Treesitter: Keywords
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.modifier"] = { link = "Keyword" },
    ["@keyword.type"] = { link = "Keyword" },
    ["@keyword.coroutine"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = colors.mauve },
    ["@keyword.operator"] = { fg = colors.mauve },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { fg = colors.mauve },
    ["@keyword.debug"] = { link = "Keyword" },
    ["@keyword.exception"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { link = "Operator" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.export"] = { fg = colors.mauve },

    -- Treesitter: Punctuation
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = colors.subtle },
    ["@punctuation.special"] = { link = "Special" },

    -- Treesitter: Comments
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.error"] = { fg = colors.base, bg = colors.red },
    ["@comment.warning"] = { fg = colors.base, bg = colors.yellow },
    ["@comment.hint"] = { fg = colors.base, bg = colors.blue },
    ["@comment.todo"] = { fg = colors.base, bg = colors.flamingo },
    ["@comment.note"] = { fg = colors.base, bg = colors.blue },

    -- Treesitter: Markup
    ["@markup"] = { fg = colors.text },
    ["@markup.strong"] = { fg = colors.red, bold = true },
    ["@markup.italic"] = { fg = colors.red, italic = true },
    ["@markup.strikethrough"] = { fg = colors.text, strikethrough = true },
    ["@markup.underline"] = { link = "Underlined" },
    ["@markup.heading"] = { fg = colors.blue },
    ["@markup.quote"] = { fg = colors.mauve },
    ["@markup.math"] = { fg = colors.blue },
    ["@markup.environment"] = { fg = colors.mauve },
    ["@markup.environment.name"] = { fg = colors.blue },
    ["@markup.link"] = { fg = colors.highlight },
    ["@markup.link.label"] = { fg = colors.highlight },
    ["@markup.link.url"] = { fg = colors.blue, italic = true, underline = true },
    ["@markup.raw"] = { fg = colors.green },
    ["@markup.list"] = { fg = colors.teal },
    ["@markup.list.checked"] = { fg = colors.green },
    ["@markup.list.unchecked"] = { fg = colors.subtle },

    -- Treesitter: Tags
    ["@tag"] = { fg = colors.blue },
    ["@tag.builtin"] = { fg = colors.blue },
    ["@tag.attribute"] = { fg = colors.yellow, italic = true },
    ["@tag.delimiter"] = { fg = colors.teal },

    -- Treesitter: Diff
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },

    -- Treesitter: Misc
    ["@error"] = { link = "Error" },
    ["@punctuation.delimiter.regex"] = { link = "@string.regexp" },

    -- Treesitter: Language-specific
    ["@function.builtin.bash"] = { fg = colors.red, italic = true },
    ["@variable.parameter.bash"] = { fg = colors.green },
    ["@constructor.lua"] = { link = "@punctuation.bracket" },
    ["@constructor.python"] = { fg = colors.teal },
    ["@constant.java"] = { fg = colors.teal },
    ["@property.css"] = { fg = colors.blue },
    ["@property.scss"] = { fg = colors.blue },
    ["@property.id.css"] = { fg = colors.yellow },
    ["@property.class.css"] = { fg = colors.yellow },
    ["@type.css"] = { fg = colors.highlight },
    ["@type.tag.css"] = { fg = colors.blue },
    ["@string.plain.css"] = { fg = colors.text },
    ["@number.css"] = { fg = colors.peach },
    ["@keyword.directive.css"] = { link = "Keyword" },
    ["@string.special.url.html"] = { fg = colors.green },
    ["@markup.link.label.html"] = { fg = colors.text },
    ["@character.special.html"] = { fg = colors.red },
    ["@keyword.import.c"] = { fg = colors.yellow },
    ["@keyword.import.cpp"] = { fg = colors.yellow },
    ["@attribute.c_sharp"] = { fg = colors.yellow },
    ["@label.yaml"] = { fg = colors.yellow },
    ["@string.special.symbol.ruby"] = { fg = colors.flamingo },
    ["@comment.warning.gitcommit"] = { fg = colors.yellow },
    ["@string.special.path.gitignore"] = { fg = colors.text },
    gitcommitSummary = { fg = colors.highlight, italic = true },
    zshKSHFunction = { link = "Function" },

    -- LSP semantic tokens
    ["@lsp.type.enumMember"] = { fg = colors.teal },
    ["@lsp.type.variable"] = {},
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.function.builtin"] = { link = "@function.builtin" },
    ["@lsp.mod.deprecated"] = { fg = colors.red, strikethrough = true },

    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { link = "FloatTitle" },

    MiniIconsBlue = { fg = colors.blue },
    MiniIconsGrey = { fg = colors.text },

    BlinkCmpLabel = { fg = colors.subtle },
    BlinkCmpLabelDeprecated = { fg = colors.muted, strikethrough = true },
    BlinkCmpKind = { fg = colors.blue },
    BlinkCmpMenu = { bg = U.darken(colors.surface, 0.500, colors.base) },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpLabelMatch = { link = "PmenuMatch" },
    BlinkCmpMenuSelection = { bg = U.darken(colors.subtle, 0.300, colors.base) },
    BlinkCmpScrollBarGutter = { bg = colors.muted },
    BlinkCmpScrollBarThumb = { bg = colors.subtle },
    BlinkCmpLabelDetail = { link = "PmenuExtra" },
    BlinkCmpLabelDescription = { link = "PmenuExtra" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },

    BlinkCmpKindText = { fg = colors.green },
    BlinkCmpKindMethod = { fg = colors.blue },
    BlinkCmpKindFunction = { fg = colors.blue },
    BlinkCmpKindConstructor = { fg = colors.blue },
    BlinkCmpKindField = { fg = colors.green },
    BlinkCmpKindVariable = { fg = colors.flamingo },
    BlinkCmpKindClass = { fg = colors.yellow },
    BlinkCmpKindInterface = { fg = colors.yellow },
    BlinkCmpKindModule = { fg = colors.blue },
    BlinkCmpKindProperty = { fg = colors.blue },
    BlinkCmpKindUnit = { fg = colors.green },
    BlinkCmpKindValue = { fg = colors.peach },
    BlinkCmpKindEnum = { fg = colors.yellow },
    BlinkCmpKindKeyword = { fg = colors.mauve },
    BlinkCmpKindSnippet = { fg = colors.flamingo },
    BlinkCmpKindColor = { fg = colors.red },
    BlinkCmpKindFile = { fg = colors.blue },
    BlinkCmpKindReference = { fg = colors.red },
    BlinkCmpKindFolder = { fg = colors.blue },
    BlinkCmpKindEnumMember = { fg = colors.teal },
    BlinkCmpKindConstant = { fg = colors.peach },
    BlinkCmpKindStruct = { fg = colors.blue },
    BlinkCmpKindEvent = { fg = colors.blue },
    BlinkCmpKindOperator = { fg = colors.teal },
    BlinkCmpKindTypeParameter = { fg = colors.flamingo },
    BlinkCmpKindCopilot = { fg = colors.teal },

    SignColumn = { bg = default_bg },
    LineNr = { fg = colors.muted, bg = default_bg },
    FoldColumn = { bg = default_bg },
    CursorLine = { bg = "None" },
    CursorLineNr = { fg = colors.highlight },
    CursorLineSign = { link = "SignColumn" },
    CursorColumn = { bg = default_bg },

    FlashBackdrop = { fg = colors.subtle },
    FlashLabel = { fg = colors.green, bg = default_bg, bold = true },
    FlashMatch = { fg = colors.highlight, bg = default_bg },
    FlashCurrent = { fg = colors.peach, bg = default_bg },
    FlashPrompt = { link = "NormalFloat" },

    GitSignsAdd = { fg = colors.green },
    GitSignsChange = { fg = colors.yellow },

    NeogitBranch = { fg = colors.peach, bold = true },
    NeogitRemote = { fg = colors.green, bold = true },
    NeogitUnmergedInto = { link = "Function" },
    NeogitUnpulledFrom = { link = "Function" },
    NeogitObjectId = { link = "Comment" },
    NeogitStash = { link = "Comment" },
    NeogitRebaseDone = { link = "Comment" },
    NeogitHunkHeader = {
      bg = U.darken(colors.blue, 0.095, colors.base),
      fg = U.darken(colors.blue, 0.5, colors.base),
    },
    NeogitHunkHeaderHighlight = { bg = U.darken(colors.blue, 0.215, colors.base), fg = colors.blue },
    NeogitDiffContext = { bg = default_bg },
    NeogitDiffContextHighlight = { bg = colors.surface },
    NeogitDiffAdd = {
      bg = U.darken(colors.green, 0.095, colors.base),
      fg = U.darken(colors.green, 0.800, colors.base),
    },
    NeogitDiffAddHighlight = {
      bg = U.darken(colors.green, 0.345, colors.base),
      fg = U.lighten(colors.green, 0.850, colors.text),
    },
    NeogitDiffDelete = {
      bg = U.darken(colors.red, 0.095, colors.base),
      fg = U.darken(colors.red, 0.800, colors.base),
    },
    NeogitDiffDeleteHighlight = {
      bg = U.darken(colors.red, 0.345, colors.base),
      fg = U.lighten(colors.red, 0.850, colors.text),
    },
    NeogitDiffHeader = { fg = colors.blue, bg = default_bg, bold = true },
    NeogitDiffHeaderHighlight = { fg = colors.peach, bg = default_bg, bold = true },
    NeogitCommitViewHeader = {
      bg = U.darken(colors.blue, 0.300, colors.base),
      fg = U.lighten(colors.blue, 0.800, colors.text),
    },
    NeogitChangeModified = { fg = colors.blue, bold = true },
    NeogitChangeDeleted = { fg = colors.red, bold = true },
    NeogitChangeAdded = { fg = colors.green, bold = true },
    NeogitChangeRenamed = { fg = colors.mauve, bold = true },
    NeogitChangeUpdated = { fg = colors.peach, bold = true },
    NeogitChangeCopied = { fg = colors.mauve, bold = true },
    NeogitChangeBothModified = { fg = colors.yellow, bold = true },
    NeogitChangeNewFile = { fg = colors.green, bold = true },
    NeogitSectionHeader = { fg = colors.mauve, bold = true },
    NeogitUntrackedfiles = { fg = colors.mauve, bold = true },
    NeogitUnstagedchanges = { fg = colors.mauve, bold = true },
    NeogitUnmergedchanges = { fg = colors.mauve, bold = true },
    NeogitUnpulledchanges = { fg = colors.mauve, bold = true },
    NeogitRecentcommits = { fg = colors.mauve, bold = true },
    NeogitStagedchanges = { fg = colors.mauve, bold = true },
    NeogitStashes = { fg = colors.mauve, bold = true },
    NeogitRebasing = { fg = colors.mauve, bold = true },
    NeogitNotificationInfo = { fg = colors.blue },
    NeogitNotificationWarning = { fg = colors.yellow },
    NeogitNotificationError = { fg = colors.red },
    NeogitGraphRed = { fg = colors.red },
    NeogitGraphWhite = { fg = colors.text },
    NeogitGraphYellow = { fg = colors.yellow },
    NeogitGraphGreen = { fg = colors.green },
    NeogitGraphCyan = { fg = colors.blue },
    NeogitGraphBlue = { fg = colors.blue },
    NeogitGraphPurple = { fg = colors.highlight },
    NeogitGraphGray = { fg = colors.subtle },
    NeogitGraphOrange = { fg = colors.peach },
    NeogitGraphBoldRed = { fg = colors.red, bold = true },
    NeogitGraphBoldWhite = { fg = colors.text, bold = true },
    NeogitGraphBoldYellow = { fg = colors.yellow, bold = true },
    NeogitGraphBoldGreen = { fg = colors.green, bold = true },
    NeogitGraphBoldCyan = { fg = colors.blue, bold = true },
    NeogitGraphBoldBlue = { fg = colors.blue, bold = true },
    NeogitGraphBoldPurple = { fg = colors.highlight, bold = true },
    NeogitGraphBoldGray = { fg = colors.subtle, bold = true },
    NeogitPopupBold = { bold = true },
    NeogitPopupSwitchKey = { fg = colors.highlight },
    NeogitPopupOptionKey = { fg = colors.highlight },
    NeogitPopupConfigKey = { fg = colors.highlight },
    NeogitPopupActionKey = { fg = colors.highlight },
    NeogitFilePath = { fg = colors.blue, italic = true },
    NeogitUnpushedTo = { fg = colors.highlight, bold = true },
    NeogitFold = { fg = "None", bg = "None" },
    NeogitTagName = { fg = colors.yellow },
    NeogitTagDistance = { fg = colors.blue },
    NeogitWinSeparator = { link = "WinSeparator" },

    NoiceCmdline = { fg = colors.text },
    NoiceCmdlineIcon = { fg = colors.teal },
    NoiceCmdlineIconSearch = { fg = colors.yellow },
    NoiceCmdlinePopupBorder = { fg = colors.highlight },
    NoiceCmdlinePopupBorderSearch = { fg = colors.yellow },
    NoiceConfirmBorder = { fg = colors.blue },
    NoiceMini = { fg = colors.subtext, blend = 0 },
    NoicePopupmenu = { bg = default_bg },
    NoicePopup = { bg = default_bg, fg = colors.text },

    PopupBorder = { link = "FloatBorder" },

    SwitchBufferStatusColor = { fg = colors.red },

    SnacksDashboardHeader = { fg = colors.mauve },
    SnacksDashboardIcon = { fg = colors.mauve },
    SnacksDashboardDesc = { fg = colors.text },
    SnacksDashboardKey = { fg = colors.peach },
    SnacksDashboardFooter = { fg = colors.red },
    SnacksIndentScope = { fg = colors.muted },

    MiniIndentscopeSymbol = { fg = colors.muted },
    MiniStarterItemPrefix = { fg = colors.mauve },
    MiniStarterFooter = { fg = colors.yellow, italic = true },

    MiniPickBorder = { link = "FloatBorder" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { bg = colors.surface },
    MiniPickMatchMarked = { fg = colors.green, bold = true },
    MiniPickMatchRanges = { fg = colors.red, bold = true },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { fg = colors.text, bg = default_bg },
    MiniPickPromptCaret = { fg = colors.flamingo },
    MiniPickPromptPrefix = { fg = colors.flamingo },

    MiniJump2dSpot = { bg = colors.base, fg = colors.peach, bold = true, underline = true },
    MiniJump2dSpotUnique = { bg = colors.base, fg = colors.teal, bold = true },

    StatusLine = { fg = colors.text, bg = "None" },
    StatusLineNC = { link = "StatusLine" },

    DiagnosticError = { fg = colors.red },
    DiagnosticWarn = { fg = colors.yellow },
    DiagnosticInfo = { fg = colors.blue },
    DiagnosticHint = { fg = colors.teal },
    DiagnosticOk = { fg = colors.green },
    DiagnosticSignError = { fg = colors.red, bg = default_bg },
    DiagnosticSignWarn = { fg = colors.yellow, bg = default_bg },
    DiagnosticSignInfo = { fg = colors.blue, bg = default_bg },
    DiagnosticSignHint = { fg = colors.teal, bg = default_bg },
    DiagnosticSignOk = { fg = colors.green, bg = default_bg },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.teal },
    DiagnosticUnderlineOk = { undercurl = true, sp = colors.green },
    DiagnosticUnnecessary = { fg = colors.muted },

    WinSeparator = { fg = colors.muted },
    WinBar = { fg = colors.muted, bg = default_bg },
    AvanteSidebarWinSeparator = { fg = colors.surface, bg = default_bg },

    DapUIScope = { fg = colors.teal },
    DapUIType = { fg = colors.mauve },
    DapUIValue = { fg = colors.teal },
    DapUIVariable = { fg = colors.text },
    DapUIModifiedValue = { fg = colors.peach },
    DapUIDecoration = { fg = colors.teal },
    DapUIThread = { fg = colors.green },
    DapUIStoppedThread = { fg = colors.teal },
    DapUISource = { fg = colors.highlight },
    DapUILineNumber = { fg = colors.teal },
    DapUIFloatBorder = { link = "FloatBorder" },
    DapUIWatchesEmpty = { fg = colors.flamingo },
    DapUIWatchesValue = { fg = colors.green },
    DapUIWatchesError = { fg = colors.flamingo },
    DapUIBreakpointsPath = { fg = colors.teal },
    DapUIBreakpointsInfo = { fg = colors.green },
    DapUIBreakpointsCurrentLine = { fg = colors.green, bold = true },
    DapUIBreakpointsDisabledLine = { fg = colors.muted },
    DapUIStepOver = { fg = colors.blue },
    DapUIStepOverNC = { link = "DapUIStepOver" },
    DapUIStepInto = { fg = colors.blue },
    DapUIStepIntoNC = { link = "DapUIStepInto" },
    DapUIStepBack = { fg = colors.blue },
    DapUIStepBackNC = { link = "DapUIStepBack" },
    DapUIStepOut = { fg = colors.blue },
    DapUIStepOutNC = { link = "DapUIStepOut" },
    DapUIStop = { fg = colors.red },
    DapUIStopNC = { link = "DapUIStop" },
    DapUIPlayPause = { fg = colors.green },
    DapUIPlayPauseNC = { link = "DapUIPlayPause" },
    DapUIRestart = { fg = colors.green },
    DapUIRestartNC = { link = "DapUIRestart" },
    DapUIUnavailable = { fg = colors.muted },
    DapUIUnavailableNC = { link = "DapUIUnavailable" },
    DapUIWinSelect = { fg = colors.peach },

    EdgyNormal = { bg = default_bg },
    EdgyWinBar = { bg = colors.surface, fg = "None" },
    EdgyTitle = { bg = colors.surface, fg = colors.blue },
    EdgyIconActive = { bg = colors.surface, fg = colors.peach },

    HighlightUndo = { bg = colors.red, fg = colors.base },
    HighlightRedo = { bg = colors.green, fg = colors.base },

    MarkdownCheckboxYes = { fg = colors.green },
    MarkdownCheckboxNo = { fg = colors.red },
    MarkdownCheckboxFire = { fg = colors.red },
    MarkdownCheckboxIdea = { fg = colors.yellow },
    MarkdownCheckboxStar = { fg = colors.yellow },
    MarkdownCheckboxSkipped = { fg = colors.red },
    MarkdownCheckboxQuestion = { fg = colors.yellow },
    MarkdownCheckboxInfo = { fg = colors.teal },
    MarkdownCheckboxImportant = { fg = colors.peach },

    MarkviewCode = { bg = colors.peach },

    LualineCustomScrollBar = { fg = colors.base },

    CopilotSuggestion = { fg = colors.subtle, italic = false },

    LspHoverNormal = { bg = colors.surface },
    LspHoverBorder = { bg = colors.surface, fg = colors.subtle },

    -- grug-far.nvim
    GrugFarHelpHeader = { fg = colors.blue, bold = true },
    GrugFarHelpHeaderKey = { fg = colors.peach },
    GrugFarHelpWinHeader = { fg = colors.blue, bold = true },
    GrugFarHelpWinActionPrefix = { fg = colors.peach },
    GrugFarHelpWinActionText = { fg = colors.text },
    GrugFarHelpWinActionKey = { fg = colors.yellow },
    GrugFarHelpWinActionDescription = { fg = colors.muted },
    GrugFarInputLabel = { fg = colors.mauve, bold = true },
    GrugFarInputPlaceholder = { fg = colors.muted },
    GrugFarResultsHeader = { link = "Comment" },
    GrugFarResultsStats = { link = "Comment" },
    GrugFarResultsActionMessage = { fg = colors.green },
    GrugFarResultsMatch = { link = "IncSearch" },
    GrugFarResultsMatchAdded = { link = "DiffAdd" },
    GrugFarResultsMatchRemoved = { link = "DiffDelete" },
    GrugFarResultsPath = { fg = colors.blue, underline = true },
    GrugFarResultsLineNr = { link = "LineNr" },
    GrugFarResultsLineNo = { link = "CursorLineNr" },
    GrugFarResultsColumnNr = { link = "LineNr" },
    GrugFarResultsNumbersSeparator = { link = "LineNr" },
    GrugFarResultsChangeIndicator = { fg = colors.yellow },
    GrugFarResultsRemoveIndicator = { fg = colors.red },
    GrugFarResultsAddIndicator = { fg = colors.green },
    GrugFarResultsDiffSeparatorIndicator = { fg = colors.subtle },
    GrugFarResultsCmdHeader = { fg = colors.blue, underline = true },

    -- git-conflict.nvim
    GitConflictCurrent = { bg = colors.surface },
    GitConflictIncoming = { bg = colors.surface },
    GitConflictAncestor = { bg = colors.surface },
    GitConflictCurrentLabel = { fg = colors.blue, bg = colors.surface, bold = true },
    GitConflictIncomingLabel = { fg = colors.green, bg = colors.surface, bold = true },
    GitConflictAncestorLabel = { fg = colors.mauve, bg = colors.surface, bold = true },

    -- diffview.nvim
    DiffviewDim1 = { link = "Comment" },
    DiffviewPrimary = { fg = colors.blue },
    DiffviewSecondary = { fg = colors.green },
    DiffviewFilePanelTitle = { fg = colors.blue, bold = true },
    DiffviewFilePanelCounter = { fg = colors.text },
    DiffviewFilePanelRootPath = { fg = colors.highlight, bold = true },
    DiffviewFilePanelFileName = { fg = colors.text },
    DiffviewFilePanelSelected = { fg = colors.yellow },
    DiffviewFilePanelPath = { link = "Comment" },
    DiffviewFilePanelInsertions = { fg = colors.green },
    DiffviewFilePanelDeletions = { fg = colors.red },
    DiffviewFilePanelConflicts = { fg = colors.yellow },
    DiffviewFolderName = { fg = colors.blue, bold = true },
    DiffviewFolderSign = { fg = colors.blue },
    DiffviewHash = { fg = colors.flamingo },
    DiffviewReference = { fg = colors.blue, bold = true },
    DiffviewReflogSelector = { fg = colors.mauve },
    DiffviewStatusAdded = { fg = colors.green },
    DiffviewStatusUntracked = { fg = colors.green },
    DiffviewStatusModified = { fg = colors.yellow },
    DiffviewStatusRenamed = { fg = colors.yellow },
    DiffviewStatusCopied = { fg = colors.yellow },
    DiffviewStatusTypeChange = { fg = colors.yellow },
    DiffviewStatusUnmerged = { fg = colors.yellow },
    DiffviewStatusUnknown = { fg = colors.red },
    DiffviewStatusDeleted = { fg = colors.red },
    DiffviewStatusBroken = { fg = colors.red },
    DiffviewStatusIgnored = { fg = colors.muted },

    -- oil.nvim
    OilDir = { fg = colors.blue, bold = true },
    OilDirIcon = { fg = colors.blue },
    OilLink = { fg = colors.teal },
    OilOrphanLink = { fg = colors.red },
    OilLinkTarget = { fg = colors.muted },
    OilOrphanLinkTarget = { fg = colors.red },
    OilFile = { fg = colors.text },
    OilCreate = { fg = colors.green },
    OilDelete = { fg = colors.red },
    OilMove = { fg = colors.yellow },
    OilCopy = { fg = colors.blue },
    OilChange = { fg = colors.yellow },
    OilRestore = { fg = colors.teal },
    OilPurge = { fg = colors.red, bold = true },
    OilTrash = { fg = colors.red },
    OilTrashSourcePath = { fg = colors.muted },

    -- neotest
    NeotestPassed = { fg = colors.green },
    NeotestFailed = { fg = colors.red },
    NeotestRunning = { fg = colors.yellow },
    NeotestSkipped = { fg = colors.blue },
    NeotestTest = { fg = colors.text },
    NeotestNamespace = { fg = colors.mauve },
    NeotestFocused = { bold = true, underline = true },
    NeotestFile = { fg = colors.blue },
    NeotestDir = { fg = colors.blue },
    NeotestIndent = { fg = colors.muted },
    NeotestExpandMarker = { fg = colors.muted },
    NeotestAdapterName = { fg = colors.flamingo },
    NeotestWinSelect = { fg = colors.blue, bold = true },
    NeotestMarked = { fg = colors.peach, bold = true },
    NeotestTarget = { fg = colors.red },
    NeotestUnknown = { fg = colors.text },
    NeotestWatching = { fg = colors.yellow },

    -- codediff.nvim
    CodeDiffConflictSign = { fg = colors.yellow },
    CodeDiffConflictSignResolved = { fg = colors.muted },
    CodeDiffConflictSignAccepted = { fg = colors.green },
    CodeDiffConflictSignRejected = { fg = colors.red },
    CodeDiffHistoryTitle = { link = "FloatTitle" },

    -- sidekick.nvim
    SidekickDiffAdd = { bg = U.darken(colors.green, 0.36, colors.base) },
    SidekickDiffDelete = { bg = U.darken(colors.red, 0.36, colors.base) },
    SidekickDiffContext = { bg = U.darken(colors.blue, 0.07, colors.base) },
    SidekickSign = { fg = colors.mauve },
    SidekickChat = { link = "NormalFloat" },
    SidekickCliAttached = { fg = colors.green },
    SidekickCliStarted = { fg = colors.yellow },
    SidekickCliInstalled = { fg = colors.green },
    SidekickCliMissing = { fg = colors.red },
    SidekickCliUnavailable = { fg = colors.red },
    SidekickLocFile = { fg = colors.blue, underline = true },
    SidekickLocNum = { fg = colors.peach },
    SidekickLocRow = { link = "SidekickLocDelim" },
    SidekickLocCol = { link = "SidekickLocDelim" },
    SidekickLocDelim = { fg = colors.subtle },

    -- nvim-dap-virtual-text
    NvimDapVirtualText = { fg = colors.muted, italic = true },
    NvimDapVirtualTextChanged = { fg = colors.yellow, italic = true },
    NvimDapVirtualTextError = { fg = colors.red, italic = true },
    NvimDapVirtualTextInfo = { fg = colors.blue, italic = true },

    -- GitSigns (additional variants)
    GitSignsDelete = { fg = colors.red },
    GitSignsChangedelete = { fg = colors.peach },
    GitSignsTopdelete = { fg = colors.red },
    GitSignsUntracked = { fg = colors.subtle },
    GitSignsCurrentLineBlame = { fg = colors.muted },
    GitSignsAddPreview = { link = "DiffAdd" },
    GitSignsDeletePreview = { link = "DiffDelete" },
    GitSignsAddInline = { bg = U.darken(colors.green, 0.36, colors.base) },
    GitSignsDeleteInline = { bg = U.darken(colors.red, 0.36, colors.base) },
    GitSignsChangeInline = { bg = U.darken(colors.blue, 0.14, colors.base) },
  }
end

function M.override_hl(colors_table)
  local colors = M.get(colors_table)

  for hl, col in pairs(colors) do
    vim.api.nvim_set_hl(0, hl, col)
  end
end

return M
