theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "version-control"]

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[keys.normal]
"D" = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]

[keys.insert]
"C-c" = "normal_mode"
"C-[" = "normal_mode"
